resources:
  - ../../base

patches:
  - target:
      kind: PersistentVolumeClaim
      name: rocketchat-data-claim
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: standard-rwo
