---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketchat-data-claim
  labels:
    placement: rocketchat-placement-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ocs-storagecluster-ceph-rbd
