resources:
  - ../../base

patches:
  - target:
      kind: Service
      name: rocket-chat
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
      - op: add
        path: /metadata/annotations
        value:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          
  - target:
      kind: PersistentVolumeClaim
      name: rocketchat-data-claim
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: gp2
